// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCOET9KmHodkDMt0_JiGVlSAVXxC1KSA4c',
    appId: '1:105693067664:web:58cd139433eb0b52fa5b15',
    messagingSenderId: '105693067664',
    projectId: 'mynotes-flutter-project-cfa0d',
    authDomain: 'mynotes-flutter-project-cfa0d.firebaseapp.com',
    storageBucket: 'mynotes-flutter-project-cfa0d.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAvKXrREMUhO88Ub7wMuv_gjXUSMYaLJrk',
    appId: '1:105693067664:android:a979a5c0e351022cfa5b15',
    messagingSenderId: '105693067664',
    projectId: 'mynotes-flutter-project-cfa0d',
    storageBucket: 'mynotes-flutter-project-cfa0d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDxCBhFPx9RC8nCdMI7rbTII_eyGGfu11c',
    appId: '1:105693067664:ios:80486da39545d1ecfa5b15',
    messagingSenderId: '105693067664',
    projectId: 'mynotes-flutter-project-cfa0d',
    storageBucket: 'mynotes-flutter-project-cfa0d.appspot.com',
    iosClientId: '105693067664-v0u2dgo7fgj9ga4mv0cmqebf17gmcp07.apps.googleusercontent.com',
    iosBundleId: 'com.markus.mynotes',
  );
}
